/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Batch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BatchTests
    {
        // TODO uncomment below to declare an instance variable for Batch
        //private Batch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Batch
            //instance = new Batch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Batch
        /// </summary>
        [Test]
        public void BatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Batch
            //Assert.IsInstanceOfType<Batch> (instance, "variable 'instance' is a Batch");
        }


        /// <summary>
        /// Test the property 'BatchNumber'
        /// </summary>
        [Test]
        public void BatchNumberTest()
        {
            // TODO unit test for the property 'BatchNumber'
        }
        /// <summary>
        /// Test the property 'Started'
        /// </summary>
        [Test]
        public void StartedTest()
        {
            // TODO unit test for the property 'Started'
        }
        /// <summary>
        /// Test the property 'Completed'
        /// </summary>
        [Test]
        public void CompletedTest()
        {
            // TODO unit test for the property 'Completed'
        }
        /// <summary>
        /// Test the property 'SalesCount'
        /// </summary>
        [Test]
        public void SalesCountTest()
        {
            // TODO unit test for the property 'SalesCount'
        }
        /// <summary>
        /// Test the property 'SalesSum'
        /// </summary>
        [Test]
        public void SalesSumTest()
        {
            // TODO unit test for the property 'SalesSum'
        }
        /// <summary>
        /// Test the property 'ReturnCount'
        /// </summary>
        [Test]
        public void ReturnCountTest()
        {
            // TODO unit test for the property 'ReturnCount'
        }
        /// <summary>
        /// Test the property 'ReturnSum'
        /// </summary>
        [Test]
        public void ReturnSumTest()
        {
            // TODO unit test for the property 'ReturnSum'
        }
        /// <summary>
        /// Test the property 'BatchError'
        /// </summary>
        [Test]
        public void BatchErrorTest()
        {
            // TODO unit test for the property 'BatchError'
        }

    }

}
