/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CheckTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CheckTransactionTests
    {
        // TODO uncomment below to declare an instance variable for CheckTransaction
        //private CheckTransaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CheckTransaction
            //instance = new CheckTransaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CheckTransaction
        /// </summary>
        [Test]
        public void CheckTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CheckTransaction
            //Assert.IsInstanceOfType<CheckTransaction> (instance, "variable 'instance' is a CheckTransaction");
        }


        /// <summary>
        /// Test the property 'TerminalID'
        /// </summary>
        [Test]
        public void TerminalIDTest()
        {
            // TODO unit test for the property 'TerminalID'
        }
        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Test]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'CheckNumber'
        /// </summary>
        [Test]
        public void CheckNumberTest()
        {
            // TODO unit test for the property 'CheckNumber'
        }
        /// <summary>
        /// Test the property 'RoutingNumber'
        /// </summary>
        [Test]
        public void RoutingNumberTest()
        {
            // TODO unit test for the property 'RoutingNumber'
        }
        /// <summary>
        /// Test the property 'MICRData'
        /// </summary>
        [Test]
        public void MICRDataTest()
        {
            // TODO unit test for the property 'MICRData'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'Address1'
        /// </summary>
        [Test]
        public void Address1Test()
        {
            // TODO unit test for the property 'Address1'
        }
        /// <summary>
        /// Test the property 'Address2'
        /// </summary>
        [Test]
        public void Address2Test()
        {
            // TODO unit test for the property 'Address2'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Test]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'DLNumber'
        /// </summary>
        [Test]
        public void DLNumberTest()
        {
            // TODO unit test for the property 'DLNumber'
        }
        /// <summary>
        /// Test the property 'DLState'
        /// </summary>
        [Test]
        public void DLStateTest()
        {
            // TODO unit test for the property 'DLState'
        }
        /// <summary>
        /// Test the property 'CourtesyCardID'
        /// </summary>
        [Test]
        public void CourtesyCardIDTest()
        {
            // TODO unit test for the property 'CourtesyCardID'
        }
        /// <summary>
        /// Test the property 'SSN4'
        /// </summary>
        [Test]
        public void SSN4Test()
        {
            // TODO unit test for the property 'SSN4'
        }
        /// <summary>
        /// Test the property 'DOBYear'
        /// </summary>
        [Test]
        public void DOBYearTest()
        {
            // TODO unit test for the property 'DOBYear'
        }
        /// <summary>
        /// Test the property 'CheckAmount'
        /// </summary>
        [Test]
        public void CheckAmountTest()
        {
            // TODO unit test for the property 'CheckAmount'
        }
        /// <summary>
        /// Test the property 'TranType'
        /// </summary>
        [Test]
        public void TranTypeTest()
        {
            // TODO unit test for the property 'TranType'
        }
        /// <summary>
        /// Test the property 'ProcID'
        /// </summary>
        [Test]
        public void ProcIDTest()
        {
            // TODO unit test for the property 'ProcID'
        }
        /// <summary>
        /// Test the property 'IPAddress'
        /// </summary>
        [Test]
        public void IPAddressTest()
        {
            // TODO unit test for the property 'IPAddress'
        }
        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Test]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }
        /// <summary>
        /// Test the property 'PONumber'
        /// </summary>
        [Test]
        public void PONumberTest()
        {
            // TODO unit test for the property 'PONumber'
        }
        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Test]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }
        /// <summary>
        /// Test the property 'TranNote'
        /// </summary>
        [Test]
        public void TranNoteTest()
        {
            // TODO unit test for the property 'TranNote'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'SECCode'
        /// </summary>
        [Test]
        public void SECCodeTest()
        {
            // TODO unit test for the property 'SECCode'
        }
        /// <summary>
        /// Test the property 'ProcResp'
        /// </summary>
        [Test]
        public void ProcRespTest()
        {
            // TODO unit test for the property 'ProcResp'
        }
        /// <summary>
        /// Test the property 'ProcCode'
        /// </summary>
        [Test]
        public void ProcCodeTest()
        {
            // TODO unit test for the property 'ProcCode'
        }
        /// <summary>
        /// Test the property 'ProcMess'
        /// </summary>
        [Test]
        public void ProcMessTest()
        {
            // TODO unit test for the property 'ProcMess'
        }

    }

}
