/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CheckTransactionSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CheckTransactionSettingsTests
    {
        // TODO uncomment below to declare an instance variable for CheckTransactionSettings
        //private CheckTransactionSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CheckTransactionSettings
            //instance = new CheckTransactionSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CheckTransactionSettings
        /// </summary>
        [Test]
        public void CheckTransactionSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CheckTransactionSettings
            //Assert.IsInstanceOfType<CheckTransactionSettings> (instance, "variable 'instance' is a CheckTransactionSettings");
        }


        /// <summary>
        /// Test the property 'Reader'
        /// </summary>
        [Test]
        public void ReaderTest()
        {
            // TODO unit test for the property 'Reader'
        }
        /// <summary>
        /// Test the property 'ContactName'
        /// </summary>
        [Test]
        public void ContactNameTest()
        {
            // TODO unit test for the property 'ContactName'
        }
        /// <summary>
        /// Test the property 'ContactTitle'
        /// </summary>
        [Test]
        public void ContactTitleTest()
        {
            // TODO unit test for the property 'ContactTitle'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'PhoneDefault'
        /// </summary>
        [Test]
        public void PhoneDefaultTest()
        {
            // TODO unit test for the property 'PhoneDefault'
        }
        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Test]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }
        /// <summary>
        /// Test the property 'BillingAddressDefault'
        /// </summary>
        [Test]
        public void BillingAddressDefaultTest()
        {
            // TODO unit test for the property 'BillingAddressDefault'
        }
        /// <summary>
        /// Test the property 'BillingAddress2'
        /// </summary>
        [Test]
        public void BillingAddress2Test()
        {
            // TODO unit test for the property 'BillingAddress2'
        }
        /// <summary>
        /// Test the property 'BillingCityDefault'
        /// </summary>
        [Test]
        public void BillingCityDefaultTest()
        {
            // TODO unit test for the property 'BillingCityDefault'
        }
        /// <summary>
        /// Test the property 'BillingStateDefault'
        /// </summary>
        [Test]
        public void BillingStateDefaultTest()
        {
            // TODO unit test for the property 'BillingStateDefault'
        }
        /// <summary>
        /// Test the property 'BillingZipDefault'
        /// </summary>
        [Test]
        public void BillingZipDefaultTest()
        {
            // TODO unit test for the property 'BillingZipDefault'
        }
        /// <summary>
        /// Test the property 'PONumber'
        /// </summary>
        [Test]
        public void PONumberTest()
        {
            // TODO unit test for the property 'PONumber'
        }
        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Test]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }
        /// <summary>
        /// Test the property 'BusinessName'
        /// </summary>
        [Test]
        public void BusinessNameTest()
        {
            // TODO unit test for the property 'BusinessName'
        }
        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Test]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }
        /// <summary>
        /// Test the property 'ReferenceNote'
        /// </summary>
        [Test]
        public void ReferenceNoteTest()
        {
            // TODO unit test for the property 'ReferenceNote'
        }
        /// <summary>
        /// Test the property 'DefaultSECCode'
        /// </summary>
        [Test]
        public void DefaultSECCodeTest()
        {
            // TODO unit test for the property 'DefaultSECCode'
        }

    }

}
