/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreditCardTransactionSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreditCardTransactionSettingsTests
    {
        // TODO uncomment below to declare an instance variable for CreditCardTransactionSettings
        //private CreditCardTransactionSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreditCardTransactionSettings
            //instance = new CreditCardTransactionSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreditCardTransactionSettings
        /// </summary>
        [Test]
        public void CreditCardTransactionSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreditCardTransactionSettings
            //Assert.IsInstanceOfType<CreditCardTransactionSettings> (instance, "variable 'instance' is a CreditCardTransactionSettings");
        }


        /// <summary>
        /// Test the property 'CVV'
        /// </summary>
        [Test]
        public void CVVTest()
        {
            // TODO unit test for the property 'CVV'
        }
        /// <summary>
        /// Test the property 'ContactName'
        /// </summary>
        [Test]
        public void ContactNameTest()
        {
            // TODO unit test for the property 'ContactName'
        }
        /// <summary>
        /// Test the property 'ContactTitle'
        /// </summary>
        [Test]
        public void ContactTitleTest()
        {
            // TODO unit test for the property 'ContactTitle'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Test]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }
        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Test]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'BillingAddress2'
        /// </summary>
        [Test]
        public void BillingAddress2Test()
        {
            // TODO unit test for the property 'BillingAddress2'
        }
        /// <summary>
        /// Test the property 'BillingCity'
        /// </summary>
        [Test]
        public void BillingCityTest()
        {
            // TODO unit test for the property 'BillingCity'
        }
        /// <summary>
        /// Test the property 'BillingState'
        /// </summary>
        [Test]
        public void BillingStateTest()
        {
            // TODO unit test for the property 'BillingState'
        }
        /// <summary>
        /// Test the property 'BillingZip'
        /// </summary>
        [Test]
        public void BillingZipTest()
        {
            // TODO unit test for the property 'BillingZip'
        }
        /// <summary>
        /// Test the property 'PONumber'
        /// </summary>
        [Test]
        public void PONumberTest()
        {
            // TODO unit test for the property 'PONumber'
        }
        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Test]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }
        /// <summary>
        /// Test the property 'BusinessName'
        /// </summary>
        [Test]
        public void BusinessNameTest()
        {
            // TODO unit test for the property 'BusinessName'
        }
        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Test]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }
        /// <summary>
        /// Test the property 'ReferenceNote'
        /// </summary>
        [Test]
        public void ReferenceNoteTest()
        {
            // TODO unit test for the property 'ReferenceNote'
        }
        /// <summary>
        /// Test the property 'SalesTax'
        /// </summary>
        [Test]
        public void SalesTaxTest()
        {
            // TODO unit test for the property 'SalesTax'
        }
        /// <summary>
        /// Test the property 'TaxExempt'
        /// </summary>
        [Test]
        public void TaxExemptTest()
        {
            // TODO unit test for the property 'TaxExempt'
        }
        /// <summary>
        /// Test the property 'CardTracks'
        /// </summary>
        [Test]
        public void CardTracksTest()
        {
            // TODO unit test for the property 'CardTracks'
        }
        /// <summary>
        /// Test the property 'CardZip'
        /// </summary>
        [Test]
        public void CardZipTest()
        {
            // TODO unit test for the property 'CardZip'
        }
        /// <summary>
        /// Test the property 'CardAddress'
        /// </summary>
        [Test]
        public void CardAddressTest()
        {
            // TODO unit test for the property 'CardAddress'
        }
        /// <summary>
        /// Test the property 'ItemDescription'
        /// </summary>
        [Test]
        public void ItemDescriptionTest()
        {
            // TODO unit test for the property 'ItemDescription'
        }
        /// <summary>
        /// Test the property 'DefaultTransactionType'
        /// </summary>
        [Test]
        public void DefaultTransactionTypeTest()
        {
            // TODO unit test for the property 'DefaultTransactionType'
        }

    }

}
