/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Settings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SettingsTests
    {
        // TODO uncomment below to declare an instance variable for Settings
        //private Settings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Settings
            //instance = new Settings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Settings
        /// </summary>
        [Test]
        public void SettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Settings
            //Assert.IsInstanceOfType<Settings> (instance, "variable 'instance' is a Settings");
        }


        /// <summary>
        /// Test the property 'CreditCardTransactionSettings'
        /// </summary>
        [Test]
        public void CreditCardTransactionSettingsTest()
        {
            // TODO unit test for the property 'CreditCardTransactionSettings'
        }
        /// <summary>
        /// Test the property 'CheckTransactionSettings'
        /// </summary>
        [Test]
        public void CheckTransactionSettingsTest()
        {
            // TODO unit test for the property 'CheckTransactionSettings'
        }
        /// <summary>
        /// Test the property 'Business'
        /// </summary>
        [Test]
        public void BusinessTest()
        {
            // TODO unit test for the property 'Business'
        }
        /// <summary>
        /// Test the property 'MainContact'
        /// </summary>
        [Test]
        public void MainContactTest()
        {
            // TODO unit test for the property 'MainContact'
        }
        /// <summary>
        /// Test the property 'Receipt40'
        /// </summary>
        [Test]
        public void Receipt40Test()
        {
            // TODO unit test for the property 'Receipt40'
        }
        /// <summary>
        /// Test the property 'Receipt80'
        /// </summary>
        [Test]
        public void Receipt80Test()
        {
            // TODO unit test for the property 'Receipt80'
        }
        /// <summary>
        /// Test the property 'PrintSignatureLine'
        /// </summary>
        [Test]
        public void PrintSignatureLineTest()
        {
            // TODO unit test for the property 'PrintSignatureLine'
        }
        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Test]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Test]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }
        /// <summary>
        /// Test the property 'CopyEmailReceipt'
        /// </summary>
        [Test]
        public void CopyEmailReceiptTest()
        {
            // TODO unit test for the property 'CopyEmailReceipt'
        }

    }

}
