/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Transaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionTests
    {
        // TODO uncomment below to declare an instance variable for Transaction
        //private Transaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Transaction
            //instance = new Transaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Transaction
        /// </summary>
        [Test]
        public void TransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Transaction
            //Assert.IsInstanceOfType<Transaction> (instance, "variable 'instance' is a Transaction");
        }


        /// <summary>
        /// Test the property 'SubmitTime'
        /// </summary>
        [Test]
        public void SubmitTimeTest()
        {
            // TODO unit test for the property 'SubmitTime'
        }
        /// <summary>
        /// Test the property 'TranType'
        /// </summary>
        [Test]
        public void TranTypeTest()
        {
            // TODO unit test for the property 'TranType'
        }
        /// <summary>
        /// Test the property 'TranAmt'
        /// </summary>
        [Test]
        public void TranAmtTest()
        {
            // TODO unit test for the property 'TranAmt'
        }
        /// <summary>
        /// Test the property 'TranTax'
        /// </summary>
        [Test]
        public void TranTaxTest()
        {
            // TODO unit test for the property 'TranTax'
        }
        /// <summary>
        /// Test the property 'TranInv'
        /// </summary>
        [Test]
        public void TranInvTest()
        {
            // TODO unit test for the property 'TranInv'
        }
        /// <summary>
        /// Test the property 'TranPO'
        /// </summary>
        [Test]
        public void TranPOTest()
        {
            // TODO unit test for the property 'TranPO'
        }
        /// <summary>
        /// Test the property 'TranCNum'
        /// </summary>
        [Test]
        public void TranCNumTest()
        {
            // TODO unit test for the property 'TranCNum'
        }
        /// <summary>
        /// Test the property 'TranNote'
        /// </summary>
        [Test]
        public void TranNoteTest()
        {
            // TODO unit test for the property 'TranNote'
        }
        /// <summary>
        /// Test the property 'CardNum'
        /// </summary>
        [Test]
        public void CardNumTest()
        {
            // TODO unit test for the property 'CardNum'
        }
        /// <summary>
        /// Test the property 'CardName'
        /// </summary>
        [Test]
        public void CardNameTest()
        {
            // TODO unit test for the property 'CardName'
        }
        /// <summary>
        /// Test the property 'CardExp'
        /// </summary>
        [Test]
        public void CardExpTest()
        {
            // TODO unit test for the property 'CardExp'
        }
        /// <summary>
        /// Test the property 'CardType'
        /// </summary>
        [Test]
        public void CardTypeTest()
        {
            // TODO unit test for the property 'CardType'
        }
        /// <summary>
        /// Test the property 'AVSStreet'
        /// </summary>
        [Test]
        public void AVSStreetTest()
        {
            // TODO unit test for the property 'AVSStreet'
        }
        /// <summary>
        /// Test the property 'AVSZip'
        /// </summary>
        [Test]
        public void AVSZipTest()
        {
            // TODO unit test for the property 'AVSZip'
        }
        /// <summary>
        /// Test the property 'CVVNum'
        /// </summary>
        [Test]
        public void CVVNumTest()
        {
            // TODO unit test for the property 'CVVNum'
        }
        /// <summary>
        /// Test the property 'ProcID'
        /// </summary>
        [Test]
        public void ProcIDTest()
        {
            // TODO unit test for the property 'ProcID'
        }
        /// <summary>
        /// Test the property 'ProcResp'
        /// </summary>
        [Test]
        public void ProcRespTest()
        {
            // TODO unit test for the property 'ProcResp'
        }
        /// <summary>
        /// Test the property 'ProcCode'
        /// </summary>
        [Test]
        public void ProcCodeTest()
        {
            // TODO unit test for the property 'ProcCode'
        }
        /// <summary>
        /// Test the property 'ProcMess'
        /// </summary>
        [Test]
        public void ProcMessTest()
        {
            // TODO unit test for the property 'ProcMess'
        }
        /// <summary>
        /// Test the property 'AVSCode'
        /// </summary>
        [Test]
        public void AVSCodeTest()
        {
            // TODO unit test for the property 'AVSCode'
        }
        /// <summary>
        /// Test the property 'AVSResp'
        /// </summary>
        [Test]
        public void AVSRespTest()
        {
            // TODO unit test for the property 'AVSResp'
        }
        /// <summary>
        /// Test the property 'CVVCode'
        /// </summary>
        [Test]
        public void CVVCodeTest()
        {
            // TODO unit test for the property 'CVVCode'
        }
        /// <summary>
        /// Test the property 'CVVResp'
        /// </summary>
        [Test]
        public void CVVRespTest()
        {
            // TODO unit test for the property 'CVVResp'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'BusinessName'
        /// </summary>
        [Test]
        public void BusinessNameTest()
        {
            // TODO unit test for the property 'BusinessName'
        }
        /// <summary>
        /// Test the property 'BusinessAddress'
        /// </summary>
        [Test]
        public void BusinessAddressTest()
        {
            // TODO unit test for the property 'BusinessAddress'
        }
        /// <summary>
        /// Test the property 'BusinessAddress2'
        /// </summary>
        [Test]
        public void BusinessAddress2Test()
        {
            // TODO unit test for the property 'BusinessAddress2'
        }
        /// <summary>
        /// Test the property 'BusinessCity'
        /// </summary>
        [Test]
        public void BusinessCityTest()
        {
            // TODO unit test for the property 'BusinessCity'
        }
        /// <summary>
        /// Test the property 'BusinessState'
        /// </summary>
        [Test]
        public void BusinessStateTest()
        {
            // TODO unit test for the property 'BusinessState'
        }
        /// <summary>
        /// Test the property 'BusinessZip'
        /// </summary>
        [Test]
        public void BusinessZipTest()
        {
            // TODO unit test for the property 'BusinessZip'
        }
        /// <summary>
        /// Test the property 'BusinessCountry'
        /// </summary>
        [Test]
        public void BusinessCountryTest()
        {
            // TODO unit test for the property 'BusinessCountry'
        }
        /// <summary>
        /// Test the property 'BusinessWebsite'
        /// </summary>
        [Test]
        public void BusinessWebsiteTest()
        {
            // TODO unit test for the property 'BusinessWebsite'
        }
        /// <summary>
        /// Test the property 'ContactFirstName'
        /// </summary>
        [Test]
        public void ContactFirstNameTest()
        {
            // TODO unit test for the property 'ContactFirstName'
        }
        /// <summary>
        /// Test the property 'ContactLastName'
        /// </summary>
        [Test]
        public void ContactLastNameTest()
        {
            // TODO unit test for the property 'ContactLastName'
        }
        /// <summary>
        /// Test the property 'ContactPhone'
        /// </summary>
        [Test]
        public void ContactPhoneTest()
        {
            // TODO unit test for the property 'ContactPhone'
        }
        /// <summary>
        /// Test the property 'ContactFax'
        /// </summary>
        [Test]
        public void ContactFaxTest()
        {
            // TODO unit test for the property 'ContactFax'
        }
        /// <summary>
        /// Test the property 'ContactEmail'
        /// </summary>
        [Test]
        public void ContactEmailTest()
        {
            // TODO unit test for the property 'ContactEmail'
        }
        /// <summary>
        /// Test the property 'ContactTitle'
        /// </summary>
        [Test]
        public void ContactTitleTest()
        {
            // TODO unit test for the property 'ContactTitle'
        }
        /// <summary>
        /// Test the property 'IP'
        /// </summary>
        [Test]
        public void IPTest()
        {
            // TODO unit test for the property 'IP'
        }
        /// <summary>
        /// Test the property 'TaxExempt'
        /// </summary>
        [Test]
        public void TaxExemptTest()
        {
            // TODO unit test for the property 'TaxExempt'
        }

    }

}
