/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VaultCreditCard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VaultCreditCardTests
    {
        // TODO uncomment below to declare an instance variable for VaultCreditCard
        //private VaultCreditCard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VaultCreditCard
            //instance = new VaultCreditCard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VaultCreditCard
        /// </summary>
        [Test]
        public void VaultCreditCardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VaultCreditCard
            //Assert.IsInstanceOfType<VaultCreditCard> (instance, "variable 'instance' is a VaultCreditCard");
        }


        /// <summary>
        /// Test the property 'MagneticTracks'
        /// </summary>
        [Test]
        public void MagneticTracksTest()
        {
            // TODO unit test for the property 'MagneticTracks'
        }
        /// <summary>
        /// Test the property 'Track1'
        /// </summary>
        [Test]
        public void Track1Test()
        {
            // TODO unit test for the property 'Track1'
        }
        /// <summary>
        /// Test the property 'Track2'
        /// </summary>
        [Test]
        public void Track2Test()
        {
            // TODO unit test for the property 'Track2'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'MaskedNumber'
        /// </summary>
        [Test]
        public void MaskedNumberTest()
        {
            // TODO unit test for the property 'MaskedNumber'
        }
        /// <summary>
        /// Test the property 'Holder'
        /// </summary>
        [Test]
        public void HolderTest()
        {
            // TODO unit test for the property 'Holder'
        }
        /// <summary>
        /// Test the property 'ExpDate'
        /// </summary>
        [Test]
        public void ExpDateTest()
        {
            // TODO unit test for the property 'ExpDate'
        }
        /// <summary>
        /// Test the property 'CVV'
        /// </summary>
        [Test]
        public void CVVTest()
        {
            // TODO unit test for the property 'CVV'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'ZIP'
        /// </summary>
        [Test]
        public void ZIPTest()
        {
            // TODO unit test for the property 'ZIP'
        }
        /// <summary>
        /// Test the property 'Swiped'
        /// </summary>
        [Test]
        public void SwipedTest()
        {
            // TODO unit test for the property 'Swiped'
        }
        /// <summary>
        /// Test the property 'TypeString'
        /// </summary>
        [Test]
        public void TypeStringTest()
        {
            // TODO unit test for the property 'TypeString'
        }
        /// <summary>
        /// Test the property 'CVVType'
        /// </summary>
        [Test]
        public void CVVTypeTest()
        {
            // TODO unit test for the property 'CVVType'
        }
        /// <summary>
        /// Test the property 'NotPresent'
        /// </summary>
        [Test]
        public void NotPresentTest()
        {
            // TODO unit test for the property 'NotPresent'
        }
        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Test]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
        /// <summary>
        /// Test the property 'CardID'
        /// </summary>
        [Test]
        public void CardIDTest()
        {
            // TODO unit test for the property 'CardID'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'Main'
        /// </summary>
        [Test]
        public void MainTest()
        {
            // TODO unit test for the property 'Main'
        }

    }

}
