# coding: utf-8

"""
    Connect16RESTful v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.field_info import FieldInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestFieldInfo(unittest.TestCase):
    """FieldInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldInfo(self):
        """Test FieldInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.field_info.FieldInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
