# coding: utf-8

"""
    Connect16RESTful v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cvv_presence_type import CVVPresenceType  # noqa: E501
from swagger_client.rest import ApiException


class TestCVVPresenceType(unittest.TestCase):
    """CVVPresenceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCVVPresenceType(self):
        """Test CVVPresenceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cvv_presence_type.CVVPresenceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
