# coding: utf-8

"""
    Connect16RESTful v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.virtual_terminal_api import VirtualTerminalApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVirtualTerminalApi(unittest.TestCase):
    """VirtualTerminalApi unit test stubs"""

    def setUp(self):
        self.api = VirtualTerminalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_virtual_terminal_mark_transaction_id_post(self):
        """Test case for api_v1_virtual_terminal_mark_transaction_id_post

        Used to Mark a single transaction  # noqa: E501
        """
        pass

    def test_api_v1_virtual_terminal_mark_transactions_post(self):
        """Test case for api_v1_virtual_terminal_mark_transactions_post

        Used to Mark multiple transactions at once  # noqa: E501
        """
        pass

    def test_api_v1_virtual_terminal_query_post(self):
        """Test case for api_v1_virtual_terminal_query_post

        Used for querying transaction information  # noqa: E501
        """
        pass

    def test_api_v1_virtual_terminal_submit_check_post(self):
        """Test case for api_v1_virtual_terminal_submit_check_post

        Used to submit a check transaction  # noqa: E501
        """
        pass

    def test_api_v1_virtual_terminal_submit_post(self):
        """Test case for api_v1_virtual_terminal_submit_post

        Used to submit sales and credit transaction types  # noqa: E501
        """
        pass

    def test_api_v1_virtual_terminal_update_transaction_info_transaction_id_post(self):
        """Test case for api_v1_virtual_terminal_update_transaction_info_transaction_id_post

        Used to update transaction information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
