/**
 * Connect16RESTful v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Connect16ResTfulV1);
  }
}(this, function(expect, Connect16ResTfulV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Connect16ResTfulV1.ReportingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportingApi', function() {
    describe('apiV1ReportingGetBatchesByDateBatchDateGet', function() {
      it('should call apiV1ReportingGetBatchesByDateBatchDateGet successfully', function(done) {
        //uncomment below and update the code to test apiV1ReportingGetBatchesByDateBatchDateGet
        //instance.apiV1ReportingGetBatchesByDateBatchDateGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1ReportingGetCheckTerminalSettingsBySECSecCodeGet', function() {
      it('should call apiV1ReportingGetCheckTerminalSettingsBySECSecCodeGet successfully', function(done) {
        //uncomment below and update the code to test apiV1ReportingGetCheckTerminalSettingsBySECSecCodeGet
        //instance.apiV1ReportingGetCheckTerminalSettingsBySECSecCodeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1ReportingGetCheckTerminalSettingsTerminalIDGet', function() {
      it('should call apiV1ReportingGetCheckTerminalSettingsTerminalIDGet successfully', function(done) {
        //uncomment below and update the code to test apiV1ReportingGetCheckTerminalSettingsTerminalIDGet
        //instance.apiV1ReportingGetCheckTerminalSettingsTerminalIDGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1ReportingGetCheckTerminalsGet', function() {
      it('should call apiV1ReportingGetCheckTerminalsGet successfully', function(done) {
        //uncomment below and update the code to test apiV1ReportingGetCheckTerminalsGet
        //instance.apiV1ReportingGetCheckTerminalsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1ReportingGetTransactionsByBatchBatchGet', function() {
      it('should call apiV1ReportingGetTransactionsByBatchBatchGet successfully', function(done) {
        //uncomment below and update the code to test apiV1ReportingGetTransactionsByBatchBatchGet
        //instance.apiV1ReportingGetTransactionsByBatchBatchGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1ReportingGetTransactionsByDateTransactionDateGet', function() {
      it('should call apiV1ReportingGetTransactionsByDateTransactionDateGet successfully', function(done) {
        //uncomment below and update the code to test apiV1ReportingGetTransactionsByDateTransactionDateGet
        //instance.apiV1ReportingGetTransactionsByDateTransactionDateGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
