# coding: utf-8

"""
    Connect16RESTful v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.receipt_custom_lines import ReceiptCustomLines  # noqa: E501
from swagger_client.rest import ApiException


class TestReceiptCustomLines(unittest.TestCase):
    """ReceiptCustomLines unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReceiptCustomLines(self):
        """Test ReceiptCustomLines"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.receipt_custom_lines.ReceiptCustomLines()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
