<?php
/**
 * BatchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BatchTest Class Doc Comment
 *
 * @category    Class
 * @description Batch
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BatchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Batch"
     */
    public function testBatch()
    {
    }

    /**
     * Test attribute "batch_number"
     */
    public function testPropertyBatchNumber()
    {
    }

    /**
     * Test attribute "started"
     */
    public function testPropertyStarted()
    {
    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {
    }

    /**
     * Test attribute "sales_count"
     */
    public function testPropertySalesCount()
    {
    }

    /**
     * Test attribute "sales_sum"
     */
    public function testPropertySalesSum()
    {
    }

    /**
     * Test attribute "return_count"
     */
    public function testPropertyReturnCount()
    {
    }

    /**
     * Test attribute "return_sum"
     */
    public function testPropertyReturnSum()
    {
    }

    /**
     * Test attribute "batch_error"
     */
    public function testPropertyBatchError()
    {
    }
}
