<?php
/**
 * CreditCardTransactionSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreditCardTransactionSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description CreditCardTransactionSettings
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreditCardTransactionSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreditCardTransactionSettings"
     */
    public function testCreditCardTransactionSettings()
    {
    }

    /**
     * Test attribute "cvv"
     */
    public function testPropertyCvv()
    {
    }

    /**
     * Test attribute "contact_name"
     */
    public function testPropertyContactName()
    {
    }

    /**
     * Test attribute "contact_title"
     */
    public function testPropertyContactTitle()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "billing_address2"
     */
    public function testPropertyBillingAddress2()
    {
    }

    /**
     * Test attribute "billing_city"
     */
    public function testPropertyBillingCity()
    {
    }

    /**
     * Test attribute "billing_state"
     */
    public function testPropertyBillingState()
    {
    }

    /**
     * Test attribute "billing_zip"
     */
    public function testPropertyBillingZip()
    {
    }

    /**
     * Test attribute "po_number"
     */
    public function testPropertyPoNumber()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "business_name"
     */
    public function testPropertyBusinessName()
    {
    }

    /**
     * Test attribute "customer_number"
     */
    public function testPropertyCustomerNumber()
    {
    }

    /**
     * Test attribute "reference_note"
     */
    public function testPropertyReferenceNote()
    {
    }

    /**
     * Test attribute "sales_tax"
     */
    public function testPropertySalesTax()
    {
    }

    /**
     * Test attribute "tax_exempt"
     */
    public function testPropertyTaxExempt()
    {
    }

    /**
     * Test attribute "card_tracks"
     */
    public function testPropertyCardTracks()
    {
    }

    /**
     * Test attribute "card_zip"
     */
    public function testPropertyCardZip()
    {
    }

    /**
     * Test attribute "card_address"
     */
    public function testPropertyCardAddress()
    {
    }

    /**
     * Test attribute "item_description"
     */
    public function testPropertyItemDescription()
    {
    }

    /**
     * Test attribute "default_transaction_type"
     */
    public function testPropertyDefaultTransactionType()
    {
    }
}
