<?php
/**
 * QueryTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QueryTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description QueryTransaction
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QueryTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QueryTransaction"
     */
    public function testQueryTransaction()
    {
    }

    /**
     * Test attribute "tran_sequence"
     */
    public function testPropertyTranSequence()
    {
    }

    /**
     * Test attribute "tran_batch"
     */
    public function testPropertyTranBatch()
    {
    }

    /**
     * Test attribute "tran_modified"
     */
    public function testPropertyTranModified()
    {
    }

    /**
     * Test attribute "tran_processed"
     */
    public function testPropertyTranProcessed()
    {
    }

    /**
     * Test attribute "tran_settled"
     */
    public function testPropertyTranSettled()
    {
    }

    /**
     * Test attribute "submit_time"
     */
    public function testPropertySubmitTime()
    {
    }

    /**
     * Test attribute "tran_type"
     */
    public function testPropertyTranType()
    {
    }

    /**
     * Test attribute "tran_amt"
     */
    public function testPropertyTranAmt()
    {
    }

    /**
     * Test attribute "tran_tax"
     */
    public function testPropertyTranTax()
    {
    }

    /**
     * Test attribute "tran_inv"
     */
    public function testPropertyTranInv()
    {
    }

    /**
     * Test attribute "tran_po"
     */
    public function testPropertyTranPo()
    {
    }

    /**
     * Test attribute "tran_c_num"
     */
    public function testPropertyTranCNum()
    {
    }

    /**
     * Test attribute "tran_note"
     */
    public function testPropertyTranNote()
    {
    }

    /**
     * Test attribute "card_num"
     */
    public function testPropertyCardNum()
    {
    }

    /**
     * Test attribute "card_name"
     */
    public function testPropertyCardName()
    {
    }

    /**
     * Test attribute "card_exp"
     */
    public function testPropertyCardExp()
    {
    }

    /**
     * Test attribute "avs_street"
     */
    public function testPropertyAvsStreet()
    {
    }

    /**
     * Test attribute "avs_zip"
     */
    public function testPropertyAvsZip()
    {
    }

    /**
     * Test attribute "cvv_num"
     */
    public function testPropertyCvvNum()
    {
    }

    /**
     * Test attribute "proc_id"
     */
    public function testPropertyProcId()
    {
    }

    /**
     * Test attribute "proc_resp"
     */
    public function testPropertyProcResp()
    {
    }

    /**
     * Test attribute "proc_code"
     */
    public function testPropertyProcCode()
    {
    }

    /**
     * Test attribute "proc_mess"
     */
    public function testPropertyProcMess()
    {
    }

    /**
     * Test attribute "avs_code"
     */
    public function testPropertyAvsCode()
    {
    }

    /**
     * Test attribute "avs_resp"
     */
    public function testPropertyAvsResp()
    {
    }

    /**
     * Test attribute "cvv_code"
     */
    public function testPropertyCvvCode()
    {
    }

    /**
     * Test attribute "cvv_resp"
     */
    public function testPropertyCvvResp()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "business_name"
     */
    public function testPropertyBusinessName()
    {
    }

    /**
     * Test attribute "business_address"
     */
    public function testPropertyBusinessAddress()
    {
    }

    /**
     * Test attribute "business_address2"
     */
    public function testPropertyBusinessAddress2()
    {
    }

    /**
     * Test attribute "business_city"
     */
    public function testPropertyBusinessCity()
    {
    }

    /**
     * Test attribute "business_state"
     */
    public function testPropertyBusinessState()
    {
    }

    /**
     * Test attribute "business_zip"
     */
    public function testPropertyBusinessZip()
    {
    }

    /**
     * Test attribute "business_country"
     */
    public function testPropertyBusinessCountry()
    {
    }

    /**
     * Test attribute "business_website"
     */
    public function testPropertyBusinessWebsite()
    {
    }

    /**
     * Test attribute "contact_first_name"
     */
    public function testPropertyContactFirstName()
    {
    }

    /**
     * Test attribute "contact_last_name"
     */
    public function testPropertyContactLastName()
    {
    }

    /**
     * Test attribute "contact_phone"
     */
    public function testPropertyContactPhone()
    {
    }

    /**
     * Test attribute "contact_fax"
     */
    public function testPropertyContactFax()
    {
    }

    /**
     * Test attribute "contact_email"
     */
    public function testPropertyContactEmail()
    {
    }

    /**
     * Test attribute "contact_title"
     */
    public function testPropertyContactTitle()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "tax_exempt"
     */
    public function testPropertyTaxExempt()
    {
    }
}
