<?php
/**
 * ReceiptCustomLinesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReceiptCustomLinesTest Class Doc Comment
 *
 * @category    Class
 * @description ReceiptCustomLines
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReceiptCustomLinesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReceiptCustomLines"
     */
    public function testReceiptCustomLines()
    {
    }

    /**
     * Test attribute "custom_line1"
     */
    public function testPropertyCustomLine1()
    {
    }

    /**
     * Test attribute "custom_line2"
     */
    public function testPropertyCustomLine2()
    {
    }

    /**
     * Test attribute "custom_line3"
     */
    public function testPropertyCustomLine3()
    {
    }

    /**
     * Test attribute "custom_line4"
     */
    public function testPropertyCustomLine4()
    {
    }
}
