<?php
/**
 * SettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SettingsTest Class Doc Comment
 *
 * @category    Class
 * @description Settings
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Settings"
     */
    public function testSettings()
    {
    }

    /**
     * Test attribute "credit_card_transaction_settings"
     */
    public function testPropertyCreditCardTransactionSettings()
    {
    }

    /**
     * Test attribute "check_transaction_settings"
     */
    public function testPropertyCheckTransactionSettings()
    {
    }

    /**
     * Test attribute "business"
     */
    public function testPropertyBusiness()
    {
    }

    /**
     * Test attribute "main_contact"
     */
    public function testPropertyMainContact()
    {
    }

    /**
     * Test attribute "receipt40"
     */
    public function testPropertyReceipt40()
    {
    }

    /**
     * Test attribute "receipt80"
     */
    public function testPropertyReceipt80()
    {
    }

    /**
     * Test attribute "print_signature_line"
     */
    public function testPropertyPrintSignatureLine()
    {
    }

    /**
     * Test attribute "response"
     */
    public function testPropertyResponse()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "copy_email_receipt"
     */
    public function testPropertyCopyEmailReceipt()
    {
    }
}
