<?php
/**
 * ReportingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ReportingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReportingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV1ReportingGetBatchesByDateBatchDateGet
     *
     * Used for getting batches by date.
     *
     */
    public function testApiV1ReportingGetBatchesByDateBatchDateGet()
    {
    }

    /**
     * Test case for apiV1ReportingGetCheckTerminalSettingsBySECSecCodeGet
     *
     * Used for getting check terminal settings information filtered by SEC code.
     *
     */
    public function testApiV1ReportingGetCheckTerminalSettingsBySECSecCodeGet()
    {
    }

    /**
     * Test case for apiV1ReportingGetCheckTerminalSettingsTerminalIDGet
     *
     * Used for getting check terminal settings information by the terminal ID.
     *
     */
    public function testApiV1ReportingGetCheckTerminalSettingsTerminalIDGet()
    {
    }

    /**
     * Test case for apiV1ReportingGetCheckTerminalsGet
     *
     * Used for getting check terminal information.
     *
     */
    public function testApiV1ReportingGetCheckTerminalsGet()
    {
    }

    /**
     * Test case for apiV1ReportingGetTransactionsByBatchBatchGet
     *
     * Used for getting transactions by batch.
     *
     */
    public function testApiV1ReportingGetTransactionsByBatchBatchGet()
    {
    }

    /**
     * Test case for apiV1ReportingGetTransactionsByDateTransactionDateGet
     *
     * Used for getting transactions by date.
     *
     */
    public function testApiV1ReportingGetTransactionsByDateTransactionDateGet()
    {
    }
}
