/**
 * Connect16RESTful v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Connect16ResTfulV1);
  }
}(this, function(expect, Connect16ResTfulV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Connect16ResTfulV1.CheckTransaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CheckTransaction', function() {
    it('should create an instance of CheckTransaction', function() {
      // uncomment below and update the code to test CheckTransaction
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be.a(Connect16ResTfulV1.CheckTransaction);
    });

    it('should have the property terminalID (base name: "Terminal_ID")', function() {
      // uncomment below and update the code to test the property terminalID
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property accountNumber (base name: "Account_Number")', function() {
      // uncomment below and update the code to test the property accountNumber
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property accountType (base name: "Account_Type")', function() {
      // uncomment below and update the code to test the property accountType
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property checkNumber (base name: "Check_Number")', function() {
      // uncomment below and update the code to test the property checkNumber
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property routingNumber (base name: "Routing_Number")', function() {
      // uncomment below and update the code to test the property routingNumber
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property mICRData (base name: "MICR_Data")', function() {
      // uncomment below and update the code to test the property mICRData
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "First_Name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "Last_Name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "Company_Name")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property address1 (base name: "Address1")', function() {
      // uncomment below and update the code to test the property address1
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property address2 (base name: "Address2")', function() {
      // uncomment below and update the code to test the property address2
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "City")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "State")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property zip (base name: "Zip")', function() {
      // uncomment below and update the code to test the property zip
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "Phone_Number")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property dLNumber (base name: "DL_Number")', function() {
      // uncomment below and update the code to test the property dLNumber
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property dLState (base name: "DL_State")', function() {
      // uncomment below and update the code to test the property dLState
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property courtesyCardID (base name: "Courtesy_Card_ID")', function() {
      // uncomment below and update the code to test the property courtesyCardID
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property sSN4 (base name: "SSN4")', function() {
      // uncomment below and update the code to test the property sSN4
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property dOBYear (base name: "DOB_Year")', function() {
      // uncomment below and update the code to test the property dOBYear
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property checkAmount (base name: "Check_Amount")', function() {
      // uncomment below and update the code to test the property checkAmount
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranType (base name: "Tran_Type")', function() {
      // uncomment below and update the code to test the property tranType
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property procID (base name: "Proc_ID")', function() {
      // uncomment below and update the code to test the property procID
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property iPAddress (base name: "IP_Address")', function() {
      // uncomment below and update the code to test the property iPAddress
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property customerNumber (base name: "CustomerNumber")', function() {
      // uncomment below and update the code to test the property customerNumber
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property pONumber (base name: "PONumber")', function() {
      // uncomment below and update the code to test the property pONumber
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property invoiceNumber (base name: "InvoiceNumber")', function() {
      // uncomment below and update the code to test the property invoiceNumber
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranNote (base name: "TranNote")', function() {
      // uncomment below and update the code to test the property tranNote
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property emailAddress (base name: "EmailAddress")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property sECCode (base name: "SEC_Code")', function() {
      // uncomment below and update the code to test the property sECCode
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property procResp (base name: "Proc_Resp")', function() {
      // uncomment below and update the code to test the property procResp
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property procCode (base name: "Proc_Code")', function() {
      // uncomment below and update the code to test the property procCode
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

    it('should have the property procMess (base name: "Proc_Mess")', function() {
      // uncomment below and update the code to test the property procMess
      //var instane = new Connect16ResTfulV1.CheckTransaction();
      //expect(instance).to.be();
    });

  });

}));
