/**
 * Connect16RESTful v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Connect16ResTfulV1);
  }
}(this, function(expect, Connect16ResTfulV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Connect16ResTfulV1.CreditCardTransactionSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreditCardTransactionSettings', function() {
    it('should create an instance of CreditCardTransactionSettings', function() {
      // uncomment below and update the code to test CreditCardTransactionSettings
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be.a(Connect16ResTfulV1.CreditCardTransactionSettings);
    });

    it('should have the property CVV (base name: "CVV")', function() {
      // uncomment below and update the code to test the property CVV
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property contactName (base name: "ContactName")', function() {
      // uncomment below and update the code to test the property contactName
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property contactTitle (base name: "ContactTitle")', function() {
      // uncomment below and update the code to test the property contactTitle
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property emailAddress (base name: "EmailAddress")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "Phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property fax (base name: "Fax")', function() {
      // uncomment below and update the code to test the property fax
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property billingAddress (base name: "BillingAddress")', function() {
      // uncomment below and update the code to test the property billingAddress
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property billingAddress2 (base name: "BillingAddress2")', function() {
      // uncomment below and update the code to test the property billingAddress2
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property billingCity (base name: "BillingCity")', function() {
      // uncomment below and update the code to test the property billingCity
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property billingState (base name: "BillingState")', function() {
      // uncomment below and update the code to test the property billingState
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property billingZip (base name: "BillingZip")', function() {
      // uncomment below and update the code to test the property billingZip
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property pONumber (base name: "PONumber")', function() {
      // uncomment below and update the code to test the property pONumber
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property invoiceNumber (base name: "InvoiceNumber")', function() {
      // uncomment below and update the code to test the property invoiceNumber
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property businessName (base name: "BusinessName")', function() {
      // uncomment below and update the code to test the property businessName
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property customerNumber (base name: "CustomerNumber")', function() {
      // uncomment below and update the code to test the property customerNumber
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property referenceNote (base name: "ReferenceNote")', function() {
      // uncomment below and update the code to test the property referenceNote
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property salesTax (base name: "SalesTax")', function() {
      // uncomment below and update the code to test the property salesTax
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property taxExempt (base name: "TaxExempt")', function() {
      // uncomment below and update the code to test the property taxExempt
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property cardTracks (base name: "CardTracks")', function() {
      // uncomment below and update the code to test the property cardTracks
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property cardZip (base name: "CardZip")', function() {
      // uncomment below and update the code to test the property cardZip
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property cardAddress (base name: "CardAddress")', function() {
      // uncomment below and update the code to test the property cardAddress
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property itemDescription (base name: "ItemDescription")', function() {
      // uncomment below and update the code to test the property itemDescription
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

    it('should have the property defaultTransactionType (base name: "DefaultTransactionType")', function() {
      // uncomment below and update the code to test the property defaultTransactionType
      //var instane = new Connect16ResTfulV1.CreditCardTransactionSettings();
      //expect(instance).to.be();
    });

  });

}));
