/**
 * Connect16RESTful v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Connect16ResTfulV1);
  }
}(this, function(expect, Connect16ResTfulV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Connect16ResTfulV1.VaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VaultApi', function() {
    describe('apiV1VaultDeleteVaultCardByIDVaultCardIDPost', function() {
      it('should call apiV1VaultDeleteVaultCardByIDVaultCardIDPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VaultDeleteVaultCardByIDVaultCardIDPost
        //instance.apiV1VaultDeleteVaultCardByIDVaultCardIDPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VaultDeleteVaultCheckByIDVaultCheckIDPost', function() {
      it('should call apiV1VaultDeleteVaultCheckByIDVaultCheckIDPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VaultDeleteVaultCheckByIDVaultCheckIDPost
        //instance.apiV1VaultDeleteVaultCheckByIDVaultCheckIDPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VaultGetVaultRecordReferenceGet', function() {
      it('should call apiV1VaultGetVaultRecordReferenceGet successfully', function(done) {
        //uncomment below and update the code to test apiV1VaultGetVaultRecordReferenceGet
        //instance.apiV1VaultGetVaultRecordReferenceGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VaultSaveVaultCardVaultIDPost', function() {
      it('should call apiV1VaultSaveVaultCardVaultIDPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VaultSaveVaultCardVaultIDPost
        //instance.apiV1VaultSaveVaultCardVaultIDPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VaultSaveVaultPost', function() {
      it('should call apiV1VaultSaveVaultPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VaultSaveVaultPost
        //instance.apiV1VaultSaveVaultPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VaultSearchVaultPost', function() {
      it('should call apiV1VaultSearchVaultPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VaultSearchVaultPost
        //instance.apiV1VaultSearchVaultPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VaultSubmitCheckWithVaultCheckIDVaultCheckIDPost', function() {
      it('should call apiV1VaultSubmitCheckWithVaultCheckIDVaultCheckIDPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VaultSubmitCheckWithVaultCheckIDVaultCheckIDPost
        //instance.apiV1VaultSubmitCheckWithVaultCheckIDVaultCheckIDPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VaultSubmitWithVaultCardIDVaultCardIDPost', function() {
      it('should call apiV1VaultSubmitWithVaultCardIDVaultCardIDPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VaultSubmitWithVaultCardIDVaultCardIDPost
        //instance.apiV1VaultSubmitWithVaultCardIDVaultCardIDPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
