/**
 * Connect16RESTful v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Connect16ResTfulV1);
  }
}(this, function(expect, Connect16ResTfulV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Connect16ResTfulV1.VirtualTerminalApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VirtualTerminalApi', function() {
    describe('apiV1VirtualTerminalMarkTransactionIDPost', function() {
      it('should call apiV1VirtualTerminalMarkTransactionIDPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VirtualTerminalMarkTransactionIDPost
        //instance.apiV1VirtualTerminalMarkTransactionIDPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VirtualTerminalMarkTransactionsPost', function() {
      it('should call apiV1VirtualTerminalMarkTransactionsPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VirtualTerminalMarkTransactionsPost
        //instance.apiV1VirtualTerminalMarkTransactionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VirtualTerminalQueryPost', function() {
      it('should call apiV1VirtualTerminalQueryPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VirtualTerminalQueryPost
        //instance.apiV1VirtualTerminalQueryPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VirtualTerminalSubmitCheckPost', function() {
      it('should call apiV1VirtualTerminalSubmitCheckPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VirtualTerminalSubmitCheckPost
        //instance.apiV1VirtualTerminalSubmitCheckPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VirtualTerminalSubmitPost', function() {
      it('should call apiV1VirtualTerminalSubmitPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VirtualTerminalSubmitPost
        //instance.apiV1VirtualTerminalSubmitPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1VirtualTerminalUpdateTransactionInfoTransactionIDPost', function() {
      it('should call apiV1VirtualTerminalUpdateTransactionInfoTransactionIDPost successfully', function(done) {
        //uncomment below and update the code to test apiV1VirtualTerminalUpdateTransactionInfoTransactionIDPost
        //instance.apiV1VirtualTerminalUpdateTransactionInfoTransactionIDPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
