/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EmailReceipt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmailReceiptTests
    {
        // TODO uncomment below to declare an instance variable for EmailReceipt
        //private EmailReceipt instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EmailReceipt
            //instance = new EmailReceipt();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmailReceipt
        /// </summary>
        [Test]
        public void EmailReceiptInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmailReceipt
            //Assert.IsInstanceOfType<EmailReceipt> (instance, "variable 'instance' is a EmailReceipt");
        }


        /// <summary>
        /// Test the property 'TransactionID'
        /// </summary>
        [Test]
        public void TransactionIDTest()
        {
            // TODO unit test for the property 'TransactionID'
        }
        /// <summary>
        /// Test the property 'ToAddresses'
        /// </summary>
        [Test]
        public void ToAddressesTest()
        {
            // TODO unit test for the property 'ToAddresses'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Test]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Footer'
        /// </summary>
        [Test]
        public void FooterTest()
        {
            // TODO unit test for the property 'Footer'
        }

    }

}
