/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReceiptCustomLines
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReceiptCustomLinesTests
    {
        // TODO uncomment below to declare an instance variable for ReceiptCustomLines
        //private ReceiptCustomLines instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReceiptCustomLines
            //instance = new ReceiptCustomLines();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReceiptCustomLines
        /// </summary>
        [Test]
        public void ReceiptCustomLinesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReceiptCustomLines
            //Assert.IsInstanceOfType<ReceiptCustomLines> (instance, "variable 'instance' is a ReceiptCustomLines");
        }


        /// <summary>
        /// Test the property 'CustomLine1'
        /// </summary>
        [Test]
        public void CustomLine1Test()
        {
            // TODO unit test for the property 'CustomLine1'
        }
        /// <summary>
        /// Test the property 'CustomLine2'
        /// </summary>
        [Test]
        public void CustomLine2Test()
        {
            // TODO unit test for the property 'CustomLine2'
        }
        /// <summary>
        /// Test the property 'CustomLine3'
        /// </summary>
        [Test]
        public void CustomLine3Test()
        {
            // TODO unit test for the property 'CustomLine3'
        }
        /// <summary>
        /// Test the property 'CustomLine4'
        /// </summary>
        [Test]
        public void CustomLine4Test()
        {
            // TODO unit test for the property 'CustomLine4'
        }

    }

}
