/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Record
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecordTests
    {
        // TODO uncomment below to declare an instance variable for Record
        //private Record instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Record
            //instance = new Record();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Record
        /// </summary>
        [Test]
        public void RecordInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Record
            //Assert.IsInstanceOfType<Record> (instance, "variable 'instance' is a Record");
        }


        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Test]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Test]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Business'
        /// </summary>
        [Test]
        public void BusinessTest()
        {
            // TODO unit test for the property 'Business'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'PO'
        /// </summary>
        [Test]
        public void POTest()
        {
            // TODO unit test for the property 'PO'
        }
        /// <summary>
        /// Test the property 'Invoice'
        /// </summary>
        [Test]
        public void InvoiceTest()
        {
            // TODO unit test for the property 'Invoice'
        }
        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Test]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
        /// <summary>
        /// Test the property 'TaxExempt'
        /// </summary>
        [Test]
        public void TaxExemptTest()
        {
            // TODO unit test for the property 'TaxExempt'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'CreditCards'
        /// </summary>
        [Test]
        public void CreditCardsTest()
        {
            // TODO unit test for the property 'CreditCards'
        }
        /// <summary>
        /// Test the property 'Checks'
        /// </summary>
        [Test]
        public void ChecksTest()
        {
            // TODO unit test for the property 'Checks'
        }

    }

}
