/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TerminalSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TerminalSettingsTests
    {
        // TODO uncomment below to declare an instance variable for TerminalSettings
        //private TerminalSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TerminalSettings
            //instance = new TerminalSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TerminalSettings
        /// </summary>
        [Test]
        public void TerminalSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TerminalSettings
            //Assert.IsInstanceOfType<TerminalSettings> (instance, "variable 'instance' is a TerminalSettings");
        }


        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Test]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'TerminalID'
        /// </summary>
        [Test]
        public void TerminalIDTest()
        {
            // TODO unit test for the property 'TerminalID'
        }
        /// <summary>
        /// Test the property 'SECCode'
        /// </summary>
        [Test]
        public void SECCodeTest()
        {
            // TODO unit test for the property 'SECCode'
        }
        /// <summary>
        /// Test the property 'GatewayTerminal'
        /// </summary>
        [Test]
        public void GatewayTerminalTest()
        {
            // TODO unit test for the property 'GatewayTerminal'
        }
        /// <summary>
        /// Test the property 'ConsumerCredits'
        /// </summary>
        [Test]
        public void ConsumerCreditsTest()
        {
            // TODO unit test for the property 'ConsumerCredits'
        }
        /// <summary>
        /// Test the property 'DLRequired'
        /// </summary>
        [Test]
        public void DLRequiredTest()
        {
            // TODO unit test for the property 'DLRequired'
        }
        /// <summary>
        /// Test the property 'CheckVerify'
        /// </summary>
        [Test]
        public void CheckVerifyTest()
        {
            // TODO unit test for the property 'CheckVerify'
        }
        /// <summary>
        /// Test the property 'IdentityVerify'
        /// </summary>
        [Test]
        public void IdentityVerifyTest()
        {
            // TODO unit test for the property 'IdentityVerify'
        }

    }

}
