/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TransactionItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionItemTests
    {
        // TODO uncomment below to declare an instance variable for TransactionItem
        //private TransactionItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionItem
            //instance = new TransactionItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionItem
        /// </summary>
        [Test]
        public void TransactionItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionItem
            //Assert.IsInstanceOfType<TransactionItem> (instance, "variable 'instance' is a TransactionItem");
        }


        /// <summary>
        /// Test the property 'TaxIncluded'
        /// </summary>
        [Test]
        public void TaxIncludedTest()
        {
            // TODO unit test for the property 'TaxIncluded'
        }
        /// <summary>
        /// Test the property 'Credit'
        /// </summary>
        [Test]
        public void CreditTest()
        {
            // TODO unit test for the property 'Credit'
        }
        /// <summary>
        /// Test the property 'ExtendedAmount'
        /// </summary>
        [Test]
        public void ExtendedAmountTest()
        {
            // TODO unit test for the property 'ExtendedAmount'
        }
        /// <summary>
        /// Test the property 'ItemNumber'
        /// </summary>
        [Test]
        public void ItemNumberTest()
        {
            // TODO unit test for the property 'ItemNumber'
        }
        /// <summary>
        /// Test the property 'UnitCost'
        /// </summary>
        [Test]
        public void UnitCostTest()
        {
            // TODO unit test for the property 'UnitCost'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Test]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'CommodityCode'
        /// </summary>
        [Test]
        public void CommodityCodeTest()
        {
            // TODO unit test for the property 'CommodityCode'
        }
        /// <summary>
        /// Test the property 'UnitOfMeasure'
        /// </summary>
        [Test]
        public void UnitOfMeasureTest()
        {
            // TODO unit test for the property 'UnitOfMeasure'
        }

    }

}
