/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdateTransactionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateTransactionInfoTests
    {
        // TODO uncomment below to declare an instance variable for UpdateTransactionInfo
        //private UpdateTransactionInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateTransactionInfo
            //instance = new UpdateTransactionInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateTransactionInfo
        /// </summary>
        [Test]
        public void UpdateTransactionInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateTransactionInfo
            //Assert.IsInstanceOfType<UpdateTransactionInfo> (instance, "variable 'instance' is a UpdateTransactionInfo");
        }


        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Test]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }
        /// <summary>
        /// Test the property 'CustomerNumber'
        /// </summary>
        [Test]
        public void CustomerNumberTest()
        {
            // TODO unit test for the property 'CustomerNumber'
        }
        /// <summary>
        /// Test the property 'PONumber'
        /// </summary>
        [Test]
        public void PONumberTest()
        {
            // TODO unit test for the property 'PONumber'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }

    }

}
