/* 
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VaultCheck
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VaultCheckTests
    {
        // TODO uncomment below to declare an instance variable for VaultCheck
        //private VaultCheck instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VaultCheck
            //instance = new VaultCheck();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VaultCheck
        /// </summary>
        [Test]
        public void VaultCheckInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VaultCheck
            //Assert.IsInstanceOfType<VaultCheck> (instance, "variable 'instance' is a VaultCheck");
        }


        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Test]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
        /// <summary>
        /// Test the property 'CheckID'
        /// </summary>
        [Test]
        public void CheckIDTest()
        {
            // TODO unit test for the property 'CheckID'
        }
        /// <summary>
        /// Test the property 'Main'
        /// </summary>
        [Test]
        public void MainTest()
        {
            // TODO unit test for the property 'Main'
        }
        /// <summary>
        /// Test the property 'CheckRouting'
        /// </summary>
        [Test]
        public void CheckRoutingTest()
        {
            // TODO unit test for the property 'CheckRouting'
        }
        /// <summary>
        /// Test the property 'CheckAccount'
        /// </summary>
        [Test]
        public void CheckAccountTest()
        {
            // TODO unit test for the property 'CheckAccount'
        }
        /// <summary>
        /// Test the property 'CheckNumber'
        /// </summary>
        [Test]
        public void CheckNumberTest()
        {
            // TODO unit test for the property 'CheckNumber'
        }
        /// <summary>
        /// Test the property 'CheckFirstName'
        /// </summary>
        [Test]
        public void CheckFirstNameTest()
        {
            // TODO unit test for the property 'CheckFirstName'
        }
        /// <summary>
        /// Test the property 'CheckLastName'
        /// </summary>
        [Test]
        public void CheckLastNameTest()
        {
            // TODO unit test for the property 'CheckLastName'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'MaskedRouting'
        /// </summary>
        [Test]
        public void MaskedRoutingTest()
        {
            // TODO unit test for the property 'MaskedRouting'
        }
        /// <summary>
        /// Test the property 'MaskedAccount'
        /// </summary>
        [Test]
        public void MaskedAccountTest()
        {
            // TODO unit test for the property 'MaskedAccount'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }

    }

}
