<?php
/**
 * CheckTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CheckTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description CheckTransaction
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CheckTransaction"
     */
    public function testCheckTransaction()
    {
    }

    /**
     * Test attribute "terminal_id"
     */
    public function testPropertyTerminalId()
    {
    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {
    }

    /**
     * Test attribute "account_type"
     */
    public function testPropertyAccountType()
    {
    }

    /**
     * Test attribute "check_number"
     */
    public function testPropertyCheckNumber()
    {
    }

    /**
     * Test attribute "routing_number"
     */
    public function testPropertyRoutingNumber()
    {
    }

    /**
     * Test attribute "micr_data"
     */
    public function testPropertyMicrData()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "address1"
     */
    public function testPropertyAddress1()
    {
    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "dl_number"
     */
    public function testPropertyDlNumber()
    {
    }

    /**
     * Test attribute "dl_state"
     */
    public function testPropertyDlState()
    {
    }

    /**
     * Test attribute "courtesy_card_id"
     */
    public function testPropertyCourtesyCardId()
    {
    }

    /**
     * Test attribute "ssn4"
     */
    public function testPropertySsn4()
    {
    }

    /**
     * Test attribute "dob_year"
     */
    public function testPropertyDobYear()
    {
    }

    /**
     * Test attribute "check_amount"
     */
    public function testPropertyCheckAmount()
    {
    }

    /**
     * Test attribute "tran_type"
     */
    public function testPropertyTranType()
    {
    }

    /**
     * Test attribute "proc_id"
     */
    public function testPropertyProcId()
    {
    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "customer_number"
     */
    public function testPropertyCustomerNumber()
    {
    }

    /**
     * Test attribute "po_number"
     */
    public function testPropertyPoNumber()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "tran_note"
     */
    public function testPropertyTranNote()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "sec_code"
     */
    public function testPropertySecCode()
    {
    }

    /**
     * Test attribute "proc_resp"
     */
    public function testPropertyProcResp()
    {
    }

    /**
     * Test attribute "proc_code"
     */
    public function testPropertyProcCode()
    {
    }

    /**
     * Test attribute "proc_mess"
     */
    public function testPropertyProcMess()
    {
    }
}
