<?php
/**
 * TerminalSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TerminalSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description TerminalSettings
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TerminalSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TerminalSettings"
     */
    public function testTerminalSettings()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "terminal_id"
     */
    public function testPropertyTerminalId()
    {
    }

    /**
     * Test attribute "sec_code"
     */
    public function testPropertySecCode()
    {
    }

    /**
     * Test attribute "gateway_terminal"
     */
    public function testPropertyGatewayTerminal()
    {
    }

    /**
     * Test attribute "consumer_credits"
     */
    public function testPropertyConsumerCredits()
    {
    }

    /**
     * Test attribute "dl_required"
     */
    public function testPropertyDlRequired()
    {
    }

    /**
     * Test attribute "check_verify"
     */
    public function testPropertyCheckVerify()
    {
    }

    /**
     * Test attribute "identity_verify"
     */
    public function testPropertyIdentityVerify()
    {
    }
}
