<?php
/**
 * VaultCreditCardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VaultCreditCardTest Class Doc Comment
 *
 * @category    Class
 * @description VaultCreditCard
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VaultCreditCardTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VaultCreditCard"
     */
    public function testVaultCreditCard()
    {
    }

    /**
     * Test attribute "magnetic_tracks"
     */
    public function testPropertyMagneticTracks()
    {
    }

    /**
     * Test attribute "track1"
     */
    public function testPropertyTrack1()
    {
    }

    /**
     * Test attribute "track2"
     */
    public function testPropertyTrack2()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "masked_number"
     */
    public function testPropertyMaskedNumber()
    {
    }

    /**
     * Test attribute "holder"
     */
    public function testPropertyHolder()
    {
    }

    /**
     * Test attribute "exp_date"
     */
    public function testPropertyExpDate()
    {
    }

    /**
     * Test attribute "cvv"
     */
    public function testPropertyCvv()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "swiped"
     */
    public function testPropertySwiped()
    {
    }

    /**
     * Test attribute "type_string"
     */
    public function testPropertyTypeString()
    {
    }

    /**
     * Test attribute "cvv_type"
     */
    public function testPropertyCvvType()
    {
    }

    /**
     * Test attribute "not_present"
     */
    public function testPropertyNotPresent()
    {
    }

    /**
     * Test attribute "response"
     */
    public function testPropertyResponse()
    {
    }

    /**
     * Test attribute "card_id"
     */
    public function testPropertyCardId()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "main"
     */
    public function testPropertyMain()
    {
    }
}
