<?php
/**
 * VaultCheckTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VaultCheckTest Class Doc Comment
 *
 * @category    Class
 * @description VaultCheck
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VaultCheckTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VaultCheck"
     */
    public function testVaultCheck()
    {
    }

    /**
     * Test attribute "response"
     */
    public function testPropertyResponse()
    {
    }

    /**
     * Test attribute "check_id"
     */
    public function testPropertyCheckId()
    {
    }

    /**
     * Test attribute "main"
     */
    public function testPropertyMain()
    {
    }

    /**
     * Test attribute "check_routing"
     */
    public function testPropertyCheckRouting()
    {
    }

    /**
     * Test attribute "check_account"
     */
    public function testPropertyCheckAccount()
    {
    }

    /**
     * Test attribute "check_number"
     */
    public function testPropertyCheckNumber()
    {
    }

    /**
     * Test attribute "check_first_name"
     */
    public function testPropertyCheckFirstName()
    {
    }

    /**
     * Test attribute "check_last_name"
     */
    public function testPropertyCheckLastName()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "masked_routing"
     */
    public function testPropertyMaskedRouting()
    {
    }

    /**
     * Test attribute "masked_account"
     */
    public function testPropertyMaskedAccount()
    {
    }

    /**
     * Test attribute "account_type"
     */
    public function testPropertyAccountType()
    {
    }
}
