/**
 * Connect16RESTful v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Connect16ResTfulV1);
  }
}(this, function(expect, Connect16ResTfulV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Connect16ResTfulV1.QueryTransaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QueryTransaction', function() {
    it('should create an instance of QueryTransaction', function() {
      // uncomment below and update the code to test QueryTransaction
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be.a(Connect16ResTfulV1.QueryTransaction);
    });

    it('should have the property tranSequence (base name: "Tran_Sequence")', function() {
      // uncomment below and update the code to test the property tranSequence
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranBatch (base name: "Tran_Batch")', function() {
      // uncomment below and update the code to test the property tranBatch
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranModified (base name: "Tran_Modified")', function() {
      // uncomment below and update the code to test the property tranModified
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranProcessed (base name: "Tran_Processed")', function() {
      // uncomment below and update the code to test the property tranProcessed
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranSettled (base name: "Tran_Settled")', function() {
      // uncomment below and update the code to test the property tranSettled
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property submitTime (base name: "Submit_Time")', function() {
      // uncomment below and update the code to test the property submitTime
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranType (base name: "Tran_Type")', function() {
      // uncomment below and update the code to test the property tranType
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranAmt (base name: "Tran_Amt")', function() {
      // uncomment below and update the code to test the property tranAmt
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranTax (base name: "Tran_Tax")', function() {
      // uncomment below and update the code to test the property tranTax
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranInv (base name: "Tran_Inv")', function() {
      // uncomment below and update the code to test the property tranInv
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranPO (base name: "Tran_PO")', function() {
      // uncomment below and update the code to test the property tranPO
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranCNum (base name: "Tran_CNum")', function() {
      // uncomment below and update the code to test the property tranCNum
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property tranNote (base name: "Tran_Note")', function() {
      // uncomment below and update the code to test the property tranNote
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property cardNum (base name: "Card_Num")', function() {
      // uncomment below and update the code to test the property cardNum
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property cardName (base name: "Card_Name")', function() {
      // uncomment below and update the code to test the property cardName
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property cardExp (base name: "Card_Exp")', function() {
      // uncomment below and update the code to test the property cardExp
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property aVSStreet (base name: "AVS_Street")', function() {
      // uncomment below and update the code to test the property aVSStreet
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property aVSZip (base name: "AVS_Zip")', function() {
      // uncomment below and update the code to test the property aVSZip
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property cVVNum (base name: "CVV_Num")', function() {
      // uncomment below and update the code to test the property cVVNum
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property procID (base name: "Proc_ID")', function() {
      // uncomment below and update the code to test the property procID
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property procResp (base name: "Proc_Resp")', function() {
      // uncomment below and update the code to test the property procResp
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property procCode (base name: "Proc_Code")', function() {
      // uncomment below and update the code to test the property procCode
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property procMess (base name: "Proc_Mess")', function() {
      // uncomment below and update the code to test the property procMess
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property aVSCode (base name: "AVS_Code")', function() {
      // uncomment below and update the code to test the property aVSCode
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property aVSResp (base name: "AVS_Resp")', function() {
      // uncomment below and update the code to test the property aVSResp
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property cVVCode (base name: "CVV_Code")', function() {
      // uncomment below and update the code to test the property cVVCode
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property cVVResp (base name: "CVV_Resp")', function() {
      // uncomment below and update the code to test the property cVVResp
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "Items")', function() {
      // uncomment below and update the code to test the property items
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property businessName (base name: "Business_Name")', function() {
      // uncomment below and update the code to test the property businessName
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property businessAddress (base name: "Business_Address")', function() {
      // uncomment below and update the code to test the property businessAddress
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property businessAddress2 (base name: "Business_Address2")', function() {
      // uncomment below and update the code to test the property businessAddress2
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property businessCity (base name: "Business_City")', function() {
      // uncomment below and update the code to test the property businessCity
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property businessState (base name: "Business_State")', function() {
      // uncomment below and update the code to test the property businessState
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property businessZip (base name: "Business_Zip")', function() {
      // uncomment below and update the code to test the property businessZip
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property businessCountry (base name: "Business_Country")', function() {
      // uncomment below and update the code to test the property businessCountry
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property businessWebsite (base name: "Business_Website")', function() {
      // uncomment below and update the code to test the property businessWebsite
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property contactFirstName (base name: "Contact_FirstName")', function() {
      // uncomment below and update the code to test the property contactFirstName
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property contactLastName (base name: "Contact_LastName")', function() {
      // uncomment below and update the code to test the property contactLastName
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property contactPhone (base name: "Contact_Phone")', function() {
      // uncomment below and update the code to test the property contactPhone
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property contactFax (base name: "Contact_Fax")', function() {
      // uncomment below and update the code to test the property contactFax
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property contactEmail (base name: "Contact_Email")', function() {
      // uncomment below and update the code to test the property contactEmail
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property contactTitle (base name: "Contact_Title")', function() {
      // uncomment below and update the code to test the property contactTitle
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property IP (base name: "IP")', function() {
      // uncomment below and update the code to test the property IP
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

    it('should have the property taxExempt (base name: "TaxExempt")', function() {
      // uncomment below and update the code to test the property taxExempt
      //var instane = new Connect16ResTfulV1.QueryTransaction();
      //expect(instance).to.be();
    });

  });

}));
