/**
 * Connect16RESTful v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Connect16ResTfulV1);
  }
}(this, function(expect, Connect16ResTfulV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Connect16ResTfulV1.TerminalSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TerminalSettings', function() {
    it('should create an instance of TerminalSettings', function() {
      // uncomment below and update the code to test TerminalSettings
      //var instane = new Connect16ResTfulV1.TerminalSettings();
      //expect(instance).to.be.a(Connect16ResTfulV1.TerminalSettings);
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new Connect16ResTfulV1.TerminalSettings();
      //expect(instance).to.be();
    });

    it('should have the property terminalID (base name: "Terminal_ID")', function() {
      // uncomment below and update the code to test the property terminalID
      //var instane = new Connect16ResTfulV1.TerminalSettings();
      //expect(instance).to.be();
    });

    it('should have the property sECCode (base name: "SEC_Code")', function() {
      // uncomment below and update the code to test the property sECCode
      //var instane = new Connect16ResTfulV1.TerminalSettings();
      //expect(instance).to.be();
    });

    it('should have the property gatewayTerminal (base name: "Gateway_Terminal")', function() {
      // uncomment below and update the code to test the property gatewayTerminal
      //var instane = new Connect16ResTfulV1.TerminalSettings();
      //expect(instance).to.be();
    });

    it('should have the property consumerCredits (base name: "Consumer_Credits")', function() {
      // uncomment below and update the code to test the property consumerCredits
      //var instane = new Connect16ResTfulV1.TerminalSettings();
      //expect(instance).to.be();
    });

    it('should have the property dLRequired (base name: "DL_Required")', function() {
      // uncomment below and update the code to test the property dLRequired
      //var instane = new Connect16ResTfulV1.TerminalSettings();
      //expect(instance).to.be();
    });

    it('should have the property checkVerify (base name: "Check_Verify")', function() {
      // uncomment below and update the code to test the property checkVerify
      //var instane = new Connect16ResTfulV1.TerminalSettings();
      //expect(instance).to.be();
    });

    it('should have the property identityVerify (base name: "Identity_Verify")', function() {
      // uncomment below and update the code to test the property identityVerify
      //var instane = new Connect16ResTfulV1.TerminalSettings();
      //expect(instance).to.be();
    });

  });

}));
