/**
 * Connect16RESTful v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Connect16ResTfulV1);
  }
}(this, function(expect, Connect16ResTfulV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Connect16ResTfulV1.TransactionItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionItem', function() {
    it('should create an instance of TransactionItem', function() {
      // uncomment below and update the code to test TransactionItem
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be.a(Connect16ResTfulV1.TransactionItem);
    });

    it('should have the property taxIncluded (base name: "TaxIncluded")', function() {
      // uncomment below and update the code to test the property taxIncluded
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property credit (base name: "Credit")', function() {
      // uncomment below and update the code to test the property credit
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property extendedAmount (base name: "ExtendedAmount")', function() {
      // uncomment below and update the code to test the property extendedAmount
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property itemNumber (base name: "ItemNumber")', function() {
      // uncomment below and update the code to test the property itemNumber
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property unitCost (base name: "UnitCost")', function() {
      // uncomment below and update the code to test the property unitCost
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "Quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property discount (base name: "Discount")', function() {
      // uncomment below and update the code to test the property discount
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property tax (base name: "Tax")', function() {
      // uncomment below and update the code to test the property tax
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property commodityCode (base name: "CommodityCode")', function() {
      // uncomment below and update the code to test the property commodityCode
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

    it('should have the property unitOfMeasure (base name: "UnitOfMeasure")', function() {
      // uncomment below and update the code to test the property unitOfMeasure
      //var instane = new Connect16ResTfulV1.TransactionItem();
      //expect(instance).to.be();
    });

  });

}));
