/**
 * Connect16RESTful v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Connect16ResTfulV1);
  }
}(this, function(expect, Connect16ResTfulV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Connect16ResTfulV1.VaultCheck();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VaultCheck', function() {
    it('should create an instance of VaultCheck', function() {
      // uncomment below and update the code to test VaultCheck
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be.a(Connect16ResTfulV1.VaultCheck);
    });

    it('should have the property response (base name: "Response")', function() {
      // uncomment below and update the code to test the property response
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property checkID (base name: "CheckID")', function() {
      // uncomment below and update the code to test the property checkID
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property main (base name: "Main")', function() {
      // uncomment below and update the code to test the property main
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property checkRouting (base name: "CheckRouting")', function() {
      // uncomment below and update the code to test the property checkRouting
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property checkAccount (base name: "CheckAccount")', function() {
      // uncomment below and update the code to test the property checkAccount
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property checkNumber (base name: "CheckNumber")', function() {
      // uncomment below and update the code to test the property checkNumber
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property checkFirstName (base name: "CheckFirstName")', function() {
      // uncomment below and update the code to test the property checkFirstName
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property checkLastName (base name: "CheckLastName")', function() {
      // uncomment below and update the code to test the property checkLastName
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "Note")', function() {
      // uncomment below and update the code to test the property note
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property maskedRouting (base name: "MaskedRouting")', function() {
      // uncomment below and update the code to test the property maskedRouting
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property maskedAccount (base name: "MaskedAccount")', function() {
      // uncomment below and update the code to test the property maskedAccount
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

    it('should have the property accountType (base name: "AccountType")', function() {
      // uncomment below and update the code to test the property accountType
      //var instane = new Connect16ResTfulV1.VaultCheck();
      //expect(instance).to.be();
    });

  });

}));
