<?php
/**
 * VaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connect16RESTful v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * VaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV1VaultDeleteVaultCardByIDVaultCardIDPost
     *
     * Used for deleting Vault card by Vault card ID.
     *
     */
    public function testApiV1VaultDeleteVaultCardByIDVaultCardIDPost()
    {
    }

    /**
     * Test case for apiV1VaultDeleteVaultCheckByIDVaultCheckIDPost
     *
     * Used for deleting a Vault check by Vault check ID.
     *
     */
    public function testApiV1VaultDeleteVaultCheckByIDVaultCheckIDPost()
    {
    }

    /**
     * Test case for apiV1VaultGetVaultRecordReferenceGet
     *
     * Used for getting a Vault record by reference.
     *
     */
    public function testApiV1VaultGetVaultRecordReferenceGet()
    {
    }

    /**
     * Test case for apiV1VaultSaveVaultCardVaultIDPost
     *
     * Used for saving a Vault card by vauld ID.
     *
     */
    public function testApiV1VaultSaveVaultCardVaultIDPost()
    {
    }

    /**
     * Test case for apiV1VaultSaveVaultPost
     *
     * Used for saving a Vault record.
     *
     */
    public function testApiV1VaultSaveVaultPost()
    {
    }

    /**
     * Test case for apiV1VaultSearchVaultPost
     *
     * Used for searching Vault records.
     *
     */
    public function testApiV1VaultSearchVaultPost()
    {
    }

    /**
     * Test case for apiV1VaultSubmitCheckWithVaultCheckIDVaultCheckIDPost
     *
     * Used for submitting a check with a Vault check ID.
     *
     */
    public function testApiV1VaultSubmitCheckWithVaultCheckIDVaultCheckIDPost()
    {
    }

    /**
     * Test case for apiV1VaultSubmitWithVaultCardIDVaultCardIDPost
     *
     * Used for submitting with a Vault card ID.
     *
     */
    public function testApiV1VaultSubmitWithVaultCardIDVaultCardIDPost()
    {
    }
}
